// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7DBnHKeDLW_-MB97oRv2o5GLTp-dFVNs',
    appId: '1:201280312347:web:fc0f80cb10d4db103a54be',
    messagingSenderId: '201280312347',
    projectId: 'aidhd-a35b9',
    authDomain: 'aidhd-a35b9.firebaseapp.com',
    storageBucket: 'aidhd-a35b9.firebasestorage.app',
    measurementId: 'G-PRP2VVRDR8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7DBnHKeDLW_-MB97oRv2o5GLTp-dFVNs',
    appId: '1:201280312347:web:215b4b5513291b823a54be',
    messagingSenderId: '201280312347',
    projectId: 'aidhd-a35b9',
    authDomain: 'aidhd-a35b9.firebaseapp.com',
    storageBucket: 'aidhd-a35b9.firebasestorage.app',
    measurementId: 'G-2HH055P1W0',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWUjhwK0j9KhW7Kccf_B-FCeapqU75p3k',
    appId: '1:201280312347:android:37e98a5058e24f1f3a54be',
    messagingSenderId: '201280312347',
    projectId: 'aidhd-a35b9',
    storageBucket: 'aidhd-a35b9.firebasestorage.app',
  );
}
